# -*- coding: utf-8 -*-
"""HTML quick styler

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oQUmxaKrwC3YduSlBOWtO2ZKWJ7dEQV6
"""

!pip install -U transformers

!pip install transformers accelerate gradio

import torch
import gradio as gr
from transformers import AutoTokenizer, AutoModelForCausalLM

model_name = "ibm-granite/granite-3.3-2b-instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.float16,
    device_map="auto"
)

def build_prompt(user_input):

    prompt = f"""
You are a professional web developer.

Generate a modern responsive HTML webpage using HTML and CSS.

User Request:
{user_input}

Rules:
- Return complete HTML
- Include <!DOCTYPE html>
- Use modern CSS styling
- Make the page clean and responsive
"""

    return prompt

def generate_html(user_input):

    prompt = build_prompt(user_input)

    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    outputs = model.generate(
        **inputs,
        max_new_tokens=400,
        temperature=0.7,
        do_sample=True,
        pad_token_id=tokenizer.eos_token_id
    )

    result = tokenizer.decode(outputs[0], skip_special_tokens=True)

    start = result.find("<!DOCTYPE html>")
    if start != -1:
        result = result[start:]

    return result, result

def download_html(code):

    file_path = "generated_page.html"

    with open(file_path, "w") as f:
        f.write(code)

    return file_path

with gr.Blocks() as app:

    gr.Markdown("# HTML Quick Styler")
    gr.Markdown("AI Powered Website Generator")

    user_input = gr.Textbox(
        label="Describe Your Website",
        placeholder="Example: Create a modern login page",
        lines=3
    )

    generate_btn = gr.Button("Generate Website")

    html_code = gr.Code(label="Generated HTML Code", language="html")

    preview = gr.HTML(label="Live Preview")

    download_btn = gr.Button("Download HTML")

    file_output = gr.File()

    generate_btn.click(
        fn=generate_html,
        inputs=user_input,
        outputs=[html_code, preview]
    )

    download_btn.click(
        fn=download_html,
        inputs=html_code,
        outputs=file_output
    )

app.launch(share=True)